<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'YogiDisqus\Module'                 => __DIR__ . '/Module.php',
    'YogiDisqus\View\Helper\YogiDisqus' => __DIR__ . '/src/YogiDisqus/View/Helper/YogiDisqus.php',
);
